# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
  "email": "super1@example.com",
  "password": "pw123!"
}

###

POST http://127.0.0.1:8000/api/cabinet/chunking
Content-Type: application/json

{
  "cabinet_uuid": "uuid-1232-2226",
  "chinking_run": {
    "chunking_config_id": 4,
    "chunk_size": 256,
    "chunk_overlap": 21,
    "unit": "char"
  }
}
